<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
if ( ! defined( 'WPINC' ) ) {
	die;
} elseif ( ! defined( 'ABSPATH' ) ) {
    exit;
} else {
class ZheroThemeOptions {
	private $zhero_theme_options_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'zhero_theme_options_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'zhero_theme_options_page_init' ) );
	}

	public function zhero_theme_options_add_plugin_page() {
		add_menu_page(
			'Zhero Theme Options', // page_title
			'Zhero Theme Options', // menu_title
			'manage_options', // capability
			'zhero-theme-options', // menu_slug
			array( $this, 'zhero_theme_options_create_admin_page' ), // function
			'dashicons-media-interactive', // icon_url
			3 // position
		);
	}

	public function zhero_theme_options_create_admin_page() {
		$this->zhero_theme_options_options = get_option( 'zhero_theme_options_option_name' ); ?>

<div class="wrap">
    <h2>Zhero Theme Options</h2>
    <p></p>
    <?php settings_errors(); ?>

    <form method="post" action="options.php">
        <?php
					settings_fields( 'zhero_theme_options_option_group' );
					do_settings_sections( 'zhero-theme-options-admin' );
					submit_button();
				?>
    </form>
</div>
<?php }

	public function zhero_theme_options_page_init() {
		register_setting(
			'zhero_theme_options_option_group', // option_group
			'zhero_theme_options_option_name', // option_name
			array( $this, 'zhero_theme_options_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'zhero_theme_options_setting_section', // id
			'Settings', // title
			array( $this, 'zhero_theme_options_section_info' ), // callback
			'zhero-theme-options-admin' // page
		);

		add_settings_field(
			'titulo_del_modulo_0', // id
			'Titulo del modulo', // title
			array( $this, 'titulo_del_modulo_0_callback' ), // callback
			'zhero-theme-options-admin', // page
			'zhero_theme_options_setting_section' // section
		);
	}

	public function zhero_theme_options_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['titulo_del_modulo_0'] ) ) {
			$sanitary_values['titulo_del_modulo_0'] = $input['titulo_del_modulo_0'];
		}

		return $sanitary_values;
	}

	public function zhero_theme_options_section_info() {
		
	}

	public function titulo_del_modulo_0_callback() {
		?> <fieldset>
    <?php $checked = ( isset( $this->zhero_theme_options_options['titulo_del_modulo_0'] ) && $this->zhero_theme_options_options['titulo_del_modulo_0'] === 'Activar' ) ? 'checked' : '' ; ?>
    <label for="titulo_del_modulo_0-0"><input type="radio" name="zhero_theme_options_option_name[titulo_del_modulo_0]"
            id="titulo_del_modulo_0-0" value="Activar" <?php echo $checked; ?>> Si</label><br>
    <?php $checked = ( isset( $this->zhero_theme_options_options['titulo_del_modulo_0'] ) && $this->zhero_theme_options_options['titulo_del_modulo_0'] === 'Desactivar' ) ? 'checked' : '' ; ?>
    <label for="titulo_del_modulo_0-1"><input type="radio" name="zhero_theme_options_option_name[titulo_del_modulo_0]"
            id="titulo_del_modulo_0-1" value="Desactivar" <?php echo $checked; ?>> no</label></fieldset> <?php
	}

}
if ( is_admin() ) {
	$zhero_theme_options = new ZheroThemeOptions();

/* 
 * Retrieve this value with:
 * $zhero_theme_options_options = get_option( 'zhero_theme_options_option_name' ); // Array of All Options
 * $titulo_del_modulo_0 = $zhero_theme_options_options['titulo_del_modulo_0']; // Titulo del modulo
 */
}
}
?>